In [0]:
SANDBOX_NAME = # Sandbox Name
DATA_PATH = "/data/sandboxes/"+SANDBOX_NAME+"/data/"




# Datos ausentes

La mayor parte de los datasets presentan registros con uno o varios campos cuya información está ausente (**missing values**), lo que puede generar problemas al intentar representar los datos, realizar ciertas operaciones o aplicarlo a un algoritmo. Es por eso que es necesario identificar y tratar esos valores ausentes. 

Las dos estrategias de tratamiento son el borrado o la asignación un valor determinado.

`Pandas` toma a los valores `NaN` y `None` como valores ausentes.



## Identificación de missing values

La primera acción a tomar es determinar si existen valores NaNs o None dentro del dataset.

In [0]:
import pandas as  pd
import numpy as np



Creamos dataframe  con missing values

In [0]:
df = pd.DataFrame({'VarA': ['aa', None, 'cc',None],
                  'VarB': [20, 30, None,None],
                  'VarC': [1234, 3456, 6789,765],
                  'VarD': [1234, 888, None,None]
                 },
                 index=['Case1', 'Case2', 'Case3', 'Case4'])
df



Comprobamos si existe algún NaN o None en el dataframe

In [0]:
df.isnull()



En el ejemplo anterior es fácil comprobar si existe algún valor ausente, pero con dataframes más grandes es necesario recurrir a otros métodos:



Nos indica si algún elemento dentro del df es un missing value

In [0]:
df.isnull().values.any()



Comprueba que columnas tienen NaNs

In [0]:
df.isnull().any()



Nos indica el número de registros con NaNs por cada columna

In [0]:
df.isnull().sum()



Devuelve el número de missing values por cada registro

In [0]:
df.isnull().sum(axis=1)



## Eliminación de missing values

La estrategia más sencilla de tratamiento de missing values consiste en eliminar los registros que los contengan.



Eliminamos cualquier registro que contenga al menos un NaN

In [0]:
df.dropna()



Sin embargo, como vemos más abajo en el df no se han eliminado los registros con  NaNs. Para que el cambio se ejecute es necesario usar la opción inplace=True: `df.dropna(inplace=True)`

In [0]:
df



Podemos indicar un conjunto de columnas en los que eliminar los NaNs.

In [0]:
df.dropna(subset=['VarB'])



Aplicamos la condición de que todos los valores del registro sean NaNs para borrar el registro.

In [0]:
df.dropna(how='all')



O podemos aplicar un límite con un número mínimo de valores no NaNs por registro.

In [0]:
df.dropna(thresh=3)



## Asignación de valores



La otra opción de tratamiento consiste en asignar un valor determinado a las instancias con missing values. Lo hacemos con el método `fillna`, que al igual que dropna requiere
el parámetro inplace=True para persistir los cambios.

In [0]:
df.fillna('new')



Esta asignación del string 'new' se ha realizado sobre todos los elementos missing values. Para ello Pandas ha realizado un cambio en el tipo de alguna de las variables.



Comprobamos que el type antes y descués del fillna es distinto para la variable numérica

In [0]:
df['VarB'].dtype, df.fillna('new')['VarB'].dtype



Para evitar este tipo de cambios no deseados seleccionamos la columna a modificar.



Realizamos únicamente el fillna sobre la columna VarA

In [0]:
df['VarA'].fillna('new', inplace=True)
df



Podemos realizar una asignación de valores tomándo el último valor observado y propagándolo hacia adelante.

In [0]:
df['VarB'].fillna(method='ffill')

In [0]:
df['VarB']



También es posible asignar el resultado de una función, en este caso el valor medio de la columna.

In [0]:
df['VarB'].fillna(np.mean(df['VarB']))



# Ejercicios 

Dado el siguiente Dataframe

In [0]:
raw_data = {'first_name': ['Jason', 'Mary', 'Tina', 'Jake', 'Amy','Anne'], 
        'last_name': ['Miller', 'Smith', 'Ali', 'Milner', 'Cooze','Lynn'], 
        'age': [42, np.nan, 36, 24, 73,'23'], 
        'sex': ['m', np.nan, 'f', 'm', 'f','f'], 
        'preTestScore': [4, np.nan, np.nan, 2, 3, np.nan],
        'postTestScore': [25, np.nan, np.nan, 62, 70, np.nan]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])
df



- a. Determine que columna(s) tiene(n) el mayor número de NaNs.
- b. Complete las variables categóricas nulas con el valor mayoritario.
- c. Elimine los registros con mayor número de nulos
- d. Complete la variable 'preTestScore' con el valor medio
- e. Complete la variable 'postTestScore' con el valor inmediatamente posterior



##### Solución Ejercicio 1



Determine que columna(s) tiene(n) el mayor número de NaNs.

In [0]:
# Respuesta aqui



Complete las variables categóricas nulas con el valor mayoritario.

In [0]:
# Respuesta aqui



Elimine los registros con mayor número de nulos

In [0]:
# Respuesta aqui



Complete la variable 'preTestScore' con el valor medio

In [0]:
# Respuesta aqui



Complete la variable 'postTestScore' con el valor inmediatamente posterior

In [0]:
# Respuesta aqui